#cloud-config
package_update: true
packages:
  - qemu-guest-agent

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

# Ensure cloud-init runs on first boot
cloud_final_modules:
  - scripts-user
