---
# Global variables for production VMs
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_rsa
ansible_python_interpreter: /usr/bin/python3

# Common packages
common_packages:
  - curl
  - wget
  - vim
  - htop
  - git

# Docker configuration
docker_users:
  - ubuntu
